# Generated by Django 5.0.6 on 2024-07-06 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tutor_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.lesson'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
