# Generated by Django 5.0.6 on 2024-06-22 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tutor_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='experience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
